[phases.setup]
nixPkgs = ['python310']

[phases.install]
cmds = ['pip install -r requirements.txt']

[phases.build]
cmds = ['mkdir -p uploads static/generated templates']

[start]
cmd = 'python app.py'